version: '3'

services:
  redis-server:
    image: redis
  mongo_server:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  rabbitmq_server:
    image: rabbitmq
  tvw_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev

    restart: always
    volumes:
      - .:/tvw_backend
    ports:
      - 4000:4000
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - DB_CONNECTION_URL=mongodb://mongo_server/tailored_comet
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - RABBITMQ_SERVER=amqp://guest:guest@rabbitmq_server
    command: npm run dev
